[package]
name = "node"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }
tower = { workspace = true, features = ["timeout"] }
futures = { workspace = true }
uuid = { workspace = true, features = ["serde"] }
parking_lot = { workspace = true, features = ["arc_lock"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
num-traits = { workspace = true }
num-bigint = { workspace = true }
dotenvy = { workspace = true }
primitive-types = { workspace = true }
http = { workspace = true }
log = { workspace = true }
url = { workspace = true }
toml = { workspace = true }
clap = { workspace = true, features = ["derive"] }
nuts = { workspace = true, features = ["nut19"] }
starknet-types = { workspace = true }
signer = { workspace = true }
db-node = { workspace = true }
sqlx = { workspace = true, features = ["postgres", "uuid", "tls-native-tls"], default-features = false }
rusqlite = { workspace = true }
starknet-types-core = { workspace = true }
bitcoin_hashes = { workspace = true }
async-trait = { workspace = true }
liquidity-source = { workspace = true }
dashmap = { workspace = true }

# gRPC
prost = { workspace = true }
tonic = { workspace = true }
tonic-health = { workspace = true }

# OPTL
tracing = { workspace = true }
open-telemetry-tracing = { workspace = true }
tower-otel = { workspace = true }
opentelemetry = { workspace = true }

# tls optional
openssl = { workspace = true, optional = true }
tonic-tls= { workspace = true, features = ["openssl"], optional = true }

# starknet optional 
starknet-payment-indexer = { workspace = true, optional = true }
## Not optional for now as it is our only form of liquidity source
starknet-liquidity-source = { workspace = true }

[features]
default = ["starknet"]
mock = ["starknet-liquidity-source/mock"]
starknet = ["dep:starknet-payment-indexer"]
tls = ["dep:openssl", "dep:tonic-tls"]
keyset-rotation = []


[build-dependencies]
tonic-build = "0.13.0"
