services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      # Required by pg_isready
      - PGUSER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=node
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      start_period: 1s
      interval: 3s
      retries: 3

  signer:
    image: "signer"
    restart: always
    environment:
      - ROOT_KEY=tprv8ZgxMBicQKsPeb6rodrmEXb1zRucvxYJgTKDhqQkZtbz8eY4Pf2EgbsT2swBXnnbDPQChQeFrFqHN72yFxzKfFAVsHdPeRWq2xqyUT2c4wH
      - GRPC_PORT=10001
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=signer
    ports:
      - "10001:10001"
    build:
      context: ..
      dockerfile: ./dockerfiles/signer.Dockerfile
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=localhost:10001"]
      start_period: 1s
      interval: 3s
      retries: 3

  node:
    image: "node"
    restart: always
    build:
      context: ..
      dockerfile: ./dockerfiles/node.Dockerfile
      args:
        - CARGO_FEATURES=starknet
    volumes:
      - ./crates/bins/node/config/sepolia.toml:/etc/paynet/config.toml
    environment:
      - PG_URL=postgres://postgres:password@db/node
      - SIGNER_URL=http://signer:10001
      - GRPC_PORT=10003
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=node
    # export the APIBARA_TOKEN && CASHIER_PRIVATE_KEY env var in this file
    env_file: .env.sepolia.node
    command:
      - --config
      - /etc/paynet/config.toml
    ports:
      - "10003:10003"
    depends_on:
      db:
        condition: service_healthy
      signer:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=localhost:10003"]
      start_period: 1s
      interval: 3s
      retries: 3

  price-provider:
    build:
      context: ..
      dockerfile: ./dockerfiles/price-provider.Dockerfile
    restart: always
    env_file:
      - ../infra/price-provider/.env.local
    environment:
      PORT: "3007"
    ports:
      - "3007:3007"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://0.0.0.0:3007/health || exit 1"]
      start_period: 20s
      interval: 3s
      timeout: 10s
      retries: 5

volumes:
  database_data:
    driver: local
