[package]
name = "signer"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = { workspace = true }
nuts = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tonic = { workspace = true }
tonic-types = { workspace = true }
tonic-health = { workspace = true }
thiserror = { workspace = true }
tokio-stream = { workspace = true }
url = { workspace = true }
prost = { workspace = true }
dotenvy = { workspace = true }
anyhow = { workspace = true }


starknet-types = { workspace = true }

[features]
client = []
server = []

[build-dependencies]
tonic-build = "*"

